language: objective-c
osx_image: xcode9.2
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - export LC_CTYPE=en_US.UTF-8
  - set -o pipefail
  - xcodebuild -workspace CCHMapClusterController.xcworkspace -scheme 'CCHMapClusterController Example iOS' -sdk iphonesimulator -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
  - xcodebuild -workspace CCHMapClusterController.xcworkspace -scheme 'CCHMapClusterController Example OS X' -sdk macosx -configuration Debug test | xcpretty -c

